In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('TravelInsurancePrediction.csv')

In [3]:
dataset=dataset.drop(['Unnamed: 0'],axis=1)
dataset.head()

Age               Employment Type GraduateOrNot  AnnualIncome  \
0   31             Government Sector           Yes        400000   
1   31  Private Sector/Self Employed           Yes       1250000   
2   34  Private Sector/Self Employed           Yes        500000   
3   28  Private Sector/Self Employed           Yes        700000   
4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [4]:
y=dataset['TravelInsurance']
y.head()

0    0
1    0
2    1
3    0
4    0
Name: TravelInsurance, dtype: int64

In [5]:
dataset=dataset.drop(['TravelInsurance'],axis=1)
dataset.head()

Age               Employment Type GraduateOrNot  AnnualIncome  \
0   31             Government Sector           Yes        400000   
1   31  Private Sector/Self Employed           Yes       1250000   
2   34  Private Sector/Self Employed           Yes        500000   
3   28  Private Sector/Self Employed           Yes        700000   
4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  
0              6                1            No                  No  
1              7                0            No                  No  
2              4                1            No                  No  
3              3                1            No                  No  
4              8                1           Yes                  No

In [6]:
X=dataset
X.head()

Age               Employment Type GraduateOrNot  AnnualIncome  \
0   31             Government Sector           Yes        400000   
1   31  Private Sector/Self Employed           Yes       1250000   
2   34  Private Sector/Self Employed           Yes        500000   
3   28  Private Sector/Self Employed           Yes        700000   
4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  
0              6                1            No                  No  
1              7                0            No                  No  
2              4                1            No                  No  
3              3                1            No                  No  
4              8                1           Yes                  No

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [8]:
X['Employment Type']=encoder.fit_transform(X['Employment Type'])
X['GraduateOrNot']=encoder.fit_transform(X['GraduateOrNot'])
X['FrequentFlyer']=encoder.fit_transform(X['FrequentFlyer'])
X['EverTravelledAbroad']=encoder.fit_transform(X['EverTravelledAbroad'])

In [9]:
X.head()

Age  Employment Type  GraduateOrNot  AnnualIncome  FamilyMembers  \
0   31                0              1        400000              6   
1   31                1              1       1250000              7   
2   34                1              1        500000              4   
3   28                1              1        700000              3   
4   28                1              1        700000              8   

   ChronicDiseases  FrequentFlyer  EverTravelledAbroad  
0                1              0                    0  
1                0              0                    0  
2                1              0                    0  
3                1              0                    0  
4                1              1                    0

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [11]:
X_train

Age  Employment Type  GraduateOrNot  AnnualIncome  FamilyMembers  \
406    28                1              1       1200000              9   
30     30                1              0        550000              6   
1147   26                1              1       1500000              3   
1936   33                1              1       1500000              7   
421    28                0              1        300000              4   
...   ...              ...            ...           ...            ...   
1791   28                1              1       1200000              5   
1096   30                1              0       1450000              7   
1932   35                1              0        800000              4   
235    30                1              0        550000              4   
1061   31                0              1        400000              3   

      ChronicDiseases  FrequentFlyer  EverTravelledAbroad  
406                 0              0                    0  
30                  0              1                    1  
1147                0              1                    1  
1936                0              1                    1  
421                 0              0                    0  
...               ...            ...                  ...  
1791                0              0                    0  
1096                1              1                    1  
1932                1              0                    0  
235                 0              0                    0  
1061                0              0                    0  

[1589 rows x 8 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-0.56937412,  0.64124103,  0.4197211 , ..., -0.61785041,
        -0.52564743, -0.48540118],
       [ 0.11421899,  0.64124103, -2.38253449, ..., -0.61785041,
         1.90241584,  2.06015155],
       [-1.25296722,  0.64124103,  0.4197211 , ..., -0.61785041,
         1.90241584,  2.06015155],
       ...,
       [ 1.82320174,  0.64124103, -2.38253449, ...,  1.61851474,
        -0.52564743, -0.48540118],
       [ 0.11421899,  0.64124103, -2.38253449, ..., -0.61785041,
        -0.52564743, -0.48540118],
       [ 0.45601554, -1.55947602,  0.4197211 , ..., -0.61785041,
        -0.52564743, -0.48540118]])

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 2, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=2, random_state=0)

In [16]:
import pickle
pickle.dump(classifier,open('pickle_dump12.pkl','wb'))

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
X_test[0]

array([-0.56937412,  0.64124103,  0.4197211 , -0.63428534, -0.48723175,
        1.61851474, -0.52564743, -0.48540118])

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[229  24]
 [ 61  84]]


0.7864321608040201

In [20]:
import pickle
model = pickle.load(open('pickle_dump12.pkl', 'rb'))

In [21]:
input_1 = [31,'Government Sector','Yes',400000,6,1,'No','No']
input_1

[31, 'Government Sector', 'Yes', 400000, 6, 1, 'No', 'No']

In [22]:
if(input_1[1]=='Government Sector'):
    input_1[1] = 0
else:
    input_1[1] = 1
    
if(input_1[2]=='Yes'):
    input_1[2] = 1
else:
    input_1[2] = 0
    
if(input_1[6]=='No'):
    input_1[6] = 0
else:
    input_1[6] = 1
    
if(input_1[7]=='No'):
    input_1[7] = 0
else:
    input_1[7] = 1

In [23]:
input_1

[31, 0, 1, 400000, 6, 1, 0, 0]

In [24]:
output_1 = model.predict([input_1])

In [25]:
print(output_1)

[0]


In [26]:
if(output_1[0]==1):
    final_string = "Yes, target the person"
else:
    final_string = "No, leave the person"

In [27]:
final_string

'No, leave the person'